name: CI
on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # checkout rep
    - uses: actions/checkout@v1
      #setup java
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
      # install flutter action
    - uses: subosito/flutter-action@v1
      with:
          channel: 'beta'
   # Get flutter dependencies.
      name: Running Flutter dependencies
      run: | 
        flutter pub get
    # Check for any formatting issues in the code.
        flutter format --set-exit-if-changed .
    # Statically analyze the Dart code for any errors.
        flutter analyze .
    # Run widget tests for our flutter project.
        flutter test
    # Build apk.
        flutter build apk
    
    # Upload generated apk to the artifacts.
      name: generate apk to artifacts
      uses: actions/upload-artifact@master
      with:
        name: apk-release
        path: build/app/outputs/bundle/release/app-release.apk